---
- hosts: localhost

  tasks:
    - name: Create VPC
      ec2_vpc_net:
        name: ohiovpc
        region: us-east-2 
        cidr_block: 172.16.0.0/16
        tenancy: default
        dns_hostnames: yes
        aws_access_key: AKIA37JGDJNFT6C7UFEC
        aws_secret_key: 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
        state: present
      register: vpc_result

    - name: Create Public Subnet
      ec2_vpc_subnet:
        vpc_id: "{{ vpc_result.vpc.id }}"
        region: us-east-2
        az: us-east-2a
        cidr: 172.16.0.0/24
        map_public: yes
        aws_access_key: AKIA37JGDJNFT6C7UFEC
        aws_secret_key: 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
        state: present
        resource_tags:
          Name: Public Subnet
      register: public_subnet_result

    - name: Create Private Subnet
      ec2_vpc_subnet:
        vpc_id: "{{ vpc_result.vpc.id }}"
        region: us-east-2
        az: us-east-2a
        cidr: 172.16.1.0/24
        map_public: no
        aws_access_key: AKIA37JGDJNFT6C7UFEC
        aws_secret_key: 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
        state: present
        resource_tags:
          Name: Private Subnet
      register: private_subnet_result

    
    - name: Create Internet Gateway
      ec2_vpc_igw:
        vpc_id: "{{ vpc_result.vpc.id }}"
        region: us-east-2 
        aws_access_key: AKIA37JGDJNFT6C7UFEC
        aws_secret_key: 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
        state: present
        tags:
          Name: Internet Gateway
      register: igw_result

    - name: Create Public NACL
      ec2_vpc_nacl:
        name: Public NACL
        vpc_id: "{{ vpc_result.vpc.id }}"
        region: us-east-2
        aws_access_key: AKIA37JGDJNFT6C7UFEC
        aws_secret_key: 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
        state: present
        subnets: ["{{ public_subnet_result.subnet.id }}"]
        tags:
          Name: Public NACL
          Description: Public NACL

        # ingress acl rules
        ingress:
          - [100, tcp, allow, 0.0.0.0/0, null, null, 22, 22]
          - [200, tcp, allow, 0.0.0.0/0, null, null, 80, 80]
          - [300, tcp, allow, 0.0.0.0/0, null, null, 443, 443]
          - [400, icmp, allow, 0.0.0.0/0, -1, -1]
          - [500, all, allow, 0.0.0.0/0, null, null, null, null]

        # egress acl rules
        egress:
          - [100, all, allow, 0.0.0.0/0, null, null, null, null]
      register: public_acl_result


    - name: Create Private1 NACL
      ec2_vpc_nacl:
        name: Private NACL
        vpc_id: "{{ vpc_result.vpc.id }}"
        region: us-east-2
        aws_access_key: AKIA37JGDJNFT6C7UFEC
        aws_secret_key: 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
        state: present
        subnets: ["{{ private1_subnet_result.subnet.id }}"]
        tags:
          Name: Private NACL
          Description: Private NACL


        # ingress acl rules
        ingress:
          - [100, all, allow, 0.0.0.0/0, null, null, null, null]

        # egress acl rules
        egress:
          - [100, all, allow, 0.0.0.0/0, null, null, null, null]
      register: private1_acl_result


    - name: Create Web Security Group
      ec2_group:
        name: Web Security Group
        vpc_id: "{{ vpc_result.vpc.id }}"
        region: us-east-2 
        aws_access_key: AKIA37JGDJNFT6C7UFEC
        aws_secret_key: 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
        state: present
        description: public security group
        tags:
          Name: Web Security Group
        rules:
        - proto: tcp
          ports:
          - 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          ports:
          - 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          ports:
          - 443
          cidr_ip: 0.0.0.0/0
        - proto: icmp
          from_port: -1
          to_port: -1
          cidr_ip: 0.0.0.0/0
      register: web_security_group_result

    - name: Create MySQL Security Group
      ec2_group:
        name: MySQL Security Group
        vpc_id: "{{ vpc_result.vpc.id }}"
        region: us-east-2 
        aws_access_key: AKIA37JGDJNFT6C7UFEC
        aws_secret_key: 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
        state: present
        description: private security group
        tags:
          Name: MySQL Security Group
        rules:
        - proto: tcp
          ports:
          - 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          ports:
          - 3306
          group_id: ["{{ web_security_group_result.group_id }}"]
        - proto: icmp
          from_port: -1
          to_port: -1
          cidr_ip: 0.0.0.0/0
      register: mysql_security_group_result


    - name: Create an EC2 key
      ec2_key:
        aws_access_key: AKIA37JGDJNFT6C7UFEC
        aws_secret_key: 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
        name: ohio
        region: us-east-2 
      register: ec2_key_result

    - name: Save private key
      copy: content="{{ ec2_key_result.key.private_key }}" dest=/root/.ssh/ohio.pem mode=0400
      when: ec2_key_result.changed

    - name: Create EC2
      ec2:
        key_name: ohio 
        aws_access_key: AKIA37JGDJNFT6C7UFEC
        aws_secret_key: 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
        region: us-east-2 
        instance_type: t2.micro
        image: ami-03657b56516ab7912 
        user_data: |
                   #!/bin/sh
                   # Install Apache Web Server and PHP
                   sudo yum -y install httpd mysql
                   amazon-linux-extras install -y php7.2
                   # Turn on web server
                   chkconfig httpd on
                   service httpd start